const $=s=>document.querySelector(s);
function toast(msg){const el=$('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),1800)}
function productCard(p){const wished=EazyStore.wishlist().some(id=>Number(id)===Number(p.id));return `<article class="product-card" data-product-link="${p.id}"><div class="product-image"><a class="product-link" href="product.html?id=${p.id}" aria-label="View ${p.name}">${p.discount?`<span class="discount">-${p.discount}%</span>`:''}<span>${p.emoji}</span></a><button class="heart ${wished?'active':''}" data-wish="${p.id}" aria-label="${wished?'Remove':'Add'} ${p.name} ${wished?'from':'to'} wishlist">${wished?'♥':'♡'}</button></div><div class="product-info"><a class="product-name" href="product.html?id=${p.id}">${p.name}</a><div class="rating">★ ${p.rating} · ${p.reviews} reviews</div><div class="price-row"><span class="price">${money(p.price)}</span><span class="old-price">${money(p.oldPrice)}</span></div><button class="add-btn" data-add="${p.id}">Add to cart</button></div></article>`}
function renderProducts(list=products){const el=$('#productGrid');if(el)el.innerHTML=list.map(productCard).join('')}
function renderDeals(){const el=$('#dealGrid');if(el)el.innerHTML=products.filter(p=>p.deal).map(productCard).join('')}
function renderCategories(){const el=$('#categoryGrid');if(el)el.innerHTML=categories.map(c=>`<a class="category-card" href="category.html?cat=${encodeURIComponent(c.name)}" data-category-link="${c.name}"><span class="category-icon">${c.icon}</span><strong>${c.name}</strong></a>`).join('')}
function renderCart(){const box=$('#cartItems');if(!box)return;const cart=EazyStore.cart();if(!cart.length){box.innerHTML='<div class="empty-cart"><div style="font-size:50px">🛒</div><p>Your cart is empty.</p><small>Add something you love and it will appear here.</small></div>';$('#cartTotal').textContent=money(0);return}const items=cart.map(i=>{const p=products.find(x=>x.id===Number(i.id));return p?{...p,qty:Number(i.qty||1)}:null}).filter(Boolean);box.innerHTML=items.map(i=>`<a class="cart-row" href="product.html?id=${i.id}"><div class="thumb">${i.emoji}</div><div><strong>${i.name}</strong><small>${money(i.price)} × ${i.qty}</small></div></a>`).join('');$('#cartTotal').textContent=money(items.reduce((a,p)=>a+p.price*p.qty,0))}
function openCart(){const d=$('#cartDrawer'),b=$('#drawerBackdrop');if(d)d.classList.add('open');if(b)b.classList.add('show');renderCart()}
function closeCart(){const d=$('#cartDrawer'),b=$('#drawerBackdrop');if(d)d.classList.remove('open');if(b)b.classList.remove('show')}
function addToCart(id){const p=products.find(x=>x.id===Number(id));if(!p)return;EazyStore.addToCart(p.id);renderCart();toast(`${p.name} added to cart`)}
function toggleWish(id){const added=EazyStore.toggleWishlist(id);renderProducts();renderDeals();EazyStore.syncBadges();toast(added?'Added to wishlist':'Removed from wishlist')}
function search(){EazyRouter.search($('#searchInput').value)}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){e.preventDefault();e.stopPropagation();addToCart(add.dataset.add);return}const wish=e.target.closest('[data-wish]');if(wish){e.preventDefault();e.stopPropagation();toggleWish(wish.dataset.wish);return}if(e.target.closest('#cartBtn')||e.target.closest('#bottomCart')){if(location.pathname.endsWith('index.html')||location.pathname.endsWith('/'))openCart();else EazyRouter.go('cart');return}if(e.target.closest('#closeCart')||e.target.id==='drawerBackdrop'){closeCart();return}if(e.target.closest('#accountBtn')||e.target.closest('#bottomAccount')){EazyRouter.go('account');return}if(e.target.closest('#wishlistBtn')){EazyRouter.go('wishlist');return}if(e.target.closest('#cartCheckout')){EazyRouter.go('checkout');return}});
const sb=$('#searchButton'),si=$('#searchInput');if(sb)sb.addEventListener('click',search);if(si)si.addEventListener('keydown',e=>{if(e.key==='Enter')search()});
renderCategories();renderDeals();renderProducts();EazyStore.syncBadges();
const end=Date.now()+1000*60*60*9+1000*60*37;setInterval(()=>{const el=$('#countdown');if(!el)return;let left=Math.max(0,end-Date.now()),h=Math.floor(left/36e5),m=Math.floor(left%36e5/6e4),s=Math.floor(left%6e4/1e3);el.textContent=`Ends in ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`},1000);